[package]
name = "keystache"
version = "0.0.0"
description = "A Nostr key management app for desktop"
authors = ["The Node-Tec Team"]
edition = "2021"

[dependencies]
anyhow = "1.0.80"
chrono = { version = "0.4.34", features = ["alloc"] }
diesel = { version = "2.2.0", features = ["sqlite", "chrono"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
directories = "5.0.1"
iced = "0.12.1"
libsqlite3-sys = { version = "0.28.0", features = ["bundled-sqlcipher"] }
nip-55 = "0.4.0"
nostr-sdk = "0.30.0"
tracing-subscriber = "0.3.18"

[dev-dependencies]
tempfile = "3.10.0"
